[debug] > Exec(__runWatch console0, Some(f41848b1-4b1e-41ca-bd29-10d4feaa21d8), Some(CommandSource(console0)))
[debug] > Exec(sbtStashOnFailure, None, Some(CommandSource(console0)))
[debug] > Exec(__preWatch console0, None, Some(CommandSource(console0)))
[debug] > Exec(run, None, Some(CommandSource(console0)))
[debug] Evaluating tasks: Compile / run
[debug] Running task... Cancel: Signal, check cycles: false, forcegc: true
[info] compiling 2 Scala sources to C:\Users\jaber.abbas\workspace\scala\learn\target\scala-3.4.2\classes ...
[warn] -- [E190] Potential Issue Warning: C:\Users\jaber.abbas\workspace\scala\learn\src\main\scala\main.scala:24:22 
[warn] 24 |  val p1: Unit = Point(10, 10)
[warn]    |                 ^^^^^^^^^^^^^
[warn]    |Discarded non-Unit value of type com.learn.Point. You may want to use `()`.
[warn]    |
[warn]    | longer explanation available when compiling with `-explain`
[warn] one warning found
[info] done compiling
[success] Total time: 0 s, completed 10 Jul 2024, 10:20:53
[debug] > Exec(resumeFromFailure, None, Some(CommandSource(console0)))
[debug] > Exec(sbtPopOnFailure, None, Some(CommandSource(console0)))
[debug] > Exec(__postWatch console0, None, Some(CommandSource(console0)))
[debug] > Exec(resumeFromFailure, None, None)
[debug] > Exec(__waitWatch console0, None, None)
